### ISSUE TITLE
Support for path operations

### ISSUE THREAD

**Issue by petermarks** [rasviitanen/svgmacro#5]
This macro looks pretty useful! I need to do some path construction, are you intending to add any support for that? Raw SVG paths are pretty ugly to generate.

**Comment by rasviitanen** [comment]
Hi, Peter. svgmacro aims to just provide low-level SVG bindings, thus I have no plans on adding functions to automate and abstract common svg tasks, such as create paths, text-paragraphs or animations. I am howerver working on another library, which builds on top of svgmacro. It will be able to easily create SVG elements such as common animations (ease-in-out, rotate etc.), gradients, paths and much more.

I will let you know once i publish the library in approx. 1 month.
Thanks  for noticing the macro!
